apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
  namespace: football-live68-prod
spec:
  type: ClusterIP
  selector:
    app: frontend-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
