apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-prod-config
  namespace: football-live68-prod
data:
  NEXT_PUBLIC_MODE: "prod"
  NEXT_PUBLIC_API_BASE_URL: "https://api.cakeo.live"

  NODE_ENV: "Production"
  PORT: "8080"

  DATABASE_SLAVE_URL: "postgres://postgres:Hop3ChmgwIunfunREEzQ@172.26.150.29:5432/football_api"
  DATABASE_URL: "postgres://postgres:Hop3ChmgwIunfunREEzQ@172.26.150.29:5432/football_api"

  API_KEY: "bOvIuU8K17K4Kgz4Ncov"

  REDIS_HOST: "172.26.150.29"
  REDIS_PASSWORD: "bDcBJbPWjYbC8oVVYZu8"
  REDIS_PORT: "6379"
  REDIS_PREFIX: "football-api"
  REDIS_USERNAME: ""

  APP_IV: "kVXWtb7OTlYeCMWP"
  APP_SECRET: "6T8W5ZKUSQGTb8qRmytldmwSfyYzKbc2"

  THE_SPORTS_USER_KEY: "thecsunit"
  SECRET_KEY: "f684f0fe47deaf4f92fcf16e54423aea"
  
  STREAM_API_KEY: "LQhnMkpJThU2OGMmIQHPToT8gRp7xH57"
  STREAM_SECRET: "sQzIF8BD0gFBMKuLsfbsomXJyxw8bGcx"
  STREAM_API_URL: "https://api-stream.1123.live"

  PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoFob4DmzpBekPOQZj3wP
  QF4HIOCC/BB5Vh+vAta0/goJAx2Zr7TTLAl73ZHuBxCOH+zyM2Ru45gJ7oN1ZvU9
  Gcd81J1Jy+Jxo5QyyWZBJ/UiYu+djt+t11x56JiKVPDxSN+NRfxyp7wcXGt3nG1A
  fIi9S+yn4U+U31tx+7xq3Jxh6rqAQByP5sAPSKNPc12gI7PGc0HrfVkvp0ZsrrNY
  +LjRXdreaYZ+Lxj1VH14RU+Vtkmc53h8/AiqmaSuX1d76ZENwAtPHkdmE0yq4K45
  XLBtuUM2elhzFMlSVVM4aUxLZmfb3Khsh4XEzi5ldfLZ56IJp8fDHWBXN0Ao3LNE
  fnZ12OcvFwAqzRR0sLCNQGcvSXFbK9qB4O9n5zrozQOQegtoDOPq1XA9GRQXsV7C
  5WT91akgkEFh02iu1awcIzVhd1DROImoq01+8sniK6cne2pRJMhY3XjtuvBRJLim
  Dlb9+pE6IoTzpbUvazXqIfC551bYFDcda0m1OUfnmiUUukRwUKgUjUiBOwLdCyl6
  V1JsZsFna+Nu/jtM+KVXL8axQ8Or7k8qIzKc/j1b3BYstIYDPKqA70nH8Kolkv0V
  COMRWJTXMfBs5nuvCtylHc5Xr4aomBt/KE4/1CoTE0wknIpeIl+XIIJavMOphFgA
  iVK+qx3A9TVEVHE5UBE5oisCAwEAAQ==
  -----END PUBLIC KEY-----"

  PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAoFob4DmzpBekPOQZj3wPQF4HIOCC/BB5Vh+vAta0/goJAx2Z
  r7TTLAl73ZHuBxCOH+zyM2Ru45gJ7oN1ZvU9Gcd81J1Jy+Jxo5QyyWZBJ/UiYu+d
  jt+t11x56JiKVPDxSN+NRfxyp7wcXGt3nG1AfIi9S+yn4U+U31tx+7xq3Jxh6rqA
  QByP5sAPSKNPc12gI7PGc0HrfVkvp0ZsrrNY+LjRXdreaYZ+Lxj1VH14RU+Vtkmc
  53h8/AiqmaSuX1d76ZENwAtPHkdmE0yq4K45XLBtuUM2elhzFMlSVVM4aUxLZmfb
  3Khsh4XEzi5ldfLZ56IJp8fDHWBXN0Ao3LNEfnZ12OcvFwAqzRR0sLCNQGcvSXFb
  K9qB4O9n5zrozQOQegtoDOPq1XA9GRQXsV7C5WT91akgkEFh02iu1awcIzVhd1DR
  OImoq01+8sniK6cne2pRJMhY3XjtuvBRJLimDlb9+pE6IoTzpbUvazXqIfC551bY
  FDcda0m1OUfnmiUUukRwUKgUjUiBOwLdCyl6V1JsZsFna+Nu/jtM+KVXL8axQ8Or
  7k8qIzKc/j1b3BYstIYDPKqA70nH8Kolkv0VCOMRWJTXMfBs5nuvCtylHc5Xr4ao
  mBt/KE4/1CoTE0wknIpeIl+XIIJavMOphFgAiVK+qx3A9TVEVHE5UBE5oisCAwEA
  AQKCAgBywwrgV2uyLRlmWvnQL0HbF3CSnxwfusqcUOC4b2HpztTUXgL4NbpM8hys
  Xxy0Aa02PCa7kU2rpcy132/O2AV6xcMZh9ihCte58v7GFWDccBzEIinpbzzDvXOi
  fEnEsQx+00AQrrSAR6kkm+VnFunoNxUDmcQtBP/PO2tAd4EjkuihTgkr2UVEKIDH
  w9nA/2j1JF0LcEpR09q/JS/zeHhcyilNuq8jZxY4LuymI4ZIVMUZSWX6Y8lPuAQh
  IjOKGNqeNypYH7/oM8FiXqSNWSPEqqBczzXWKidy4QMD/iOJeQkdqYc5TXEfLSXF
  Sn9jAwPhO58dbWK/S4wgBtM34TVLCwG0BIld6fBo2JoBAzXAqNDrAtuoqcgE81WB
  M0IxKjpVrELzOUHwnEXddHgHFWLVOcfNR/NJCln6X5SaI7Gca8QSzua6e6DqFxuk
  C19DS40zN1qUWTz/yxfzZhbhTlqqGjglMaHCLgQtVjEbR1IgeY5xB1wM0MM3A8Vz
  46lIkgnTwfuEzJmCGoshS/mDdQ4cEL4jAQuNLP5UKNPa7aoxWTKhB/idFSFnr6T4
  WEVD7xTX+UhQSm0rjmYedJ4EeqUFl14+xkCZuBcdnUmggl6Ak3fOiB6kRz+2JeNG
  Sc4sV38v7A/LyukSH+JvcLXmCnN12Noc7WOcvBWWUnJAZhWrgQKCAQEAzaGmL90X
  9UOCF8JZEGQoKv57Y7P/98qURXazbg/C/kaVsUqeW6Y2Z4l6ZS8nljI5oGSOqSqW
  iAvMbiRqefYY2Tnl+V2iI2jEiqK3ibQaRySUkXBQooEh4Xtpn531O8k9Mt36Xq6a
  h+JOmZL2jv+3pUzDqKJFFGpA5qeEoD7xpClJQL43R5kwNHAmXYG8SxUqYQ2t7vUk
  fEGBHMvxxD7F/4m3qI9K4sUjlbWyG3C4BssOs6FoInO+xWwYhCsphOvVJKdm6lbR
  xCtF0fDY5Sjr1Sg8QxrrTArtA6dVvDKSPaa50s9NAHyV2U128KzVCRL1NwXtPxdB
  p9KhOqnjVlRZ0wKCAQEAx6EpHqSNBMy672hHqPGTuUdFUmMJcu7vEwb3PApmCh2/
  o3ds5M6LZSVar6oUbf8J1oReGWnlps5h1ZAsRmNX9vCEAgl6Lgk0C7Qhicdg09kq
  gEDH/Q2yB1ue6o7ngGCtvzS+hIHnhp4Bmft1spaJ1+XxTf3PPYJZz6oRLA/8q0Km
  WcK923KufS4jwijK1nCb/Fx5g6QyOSMXK0whMz4OgJ2wYE9N5gy6W0uXxeN6DcL6
  q6aisj6ViQWJ2DBUo2E4p2HVLDrGpc+4vcnouJI6sgLyMcw4ltgaxmsEZ71dcJWv
  e1jo39dcBbmSvgsDZxDbbmCNn8jHPxlPynInkKPHSQKCAQEAyzjDpjAKWnFSY6rG
  HMXvULZaOaoOAdUqfhAWumJHYsddb28AXDFDOUYMOW3F4NFYVGSs/RDC3kdSzVOe
  C1SlMCHhX3YjJH2JKD4xx5zAD6leTvJCLqgSVOaD96TDVUfH/LqWkvZacIq/BVXR
  6HdfBrV79PAR92AfLhVGpJwwcf3/kEWtGkyR8HEZ6XWrIkUTsgEz8aJCYa7XLB9+
  m2Uyhx6S7LpY1w7f4ThFgor+xG/v4qVU5h+f3Tq8a/rAOMZdyrDKrDQLcaUWhqpR
  oQC1Od9e1y8GdguiO+cneyw7jUR2B5qqTh3SdoTxVGBq1mHvCGcKFj0kvPgUMYbu
  z0Xj0wKCAQA0LEJ657aTUo5ok3BnDvv0qFPNvGRzzU5eQqvK3Uzdx/iV2Fh1VCXK
  QYD5+BFuzgDcN6wAKFUEy1t2XT+1BbGvsBxQC/oKng0kIefCAoGj3FXnPwcFc9bb
  ZW6bDs4iFyJRno9MQkcoP5NbkwSnsABGlKoEIBlRkge25lOmmGcIu1qOiv7jo41G
  2hAuZkrc0IFz6xc2+GrH1AvyHOtwYP+ZTZ0TDqblQN5TjeYUqeb0QckRo3NR8llS
  fkgQYFE+geI0nLUB4jqYizlVILfZxR3h+DMkIKOJiOE2ijGUi0Eoc3ZxXkM+fSJn
  vKBFWsuA3D79Ee7xm5+3Nf5MgpkkjClBAoIBABRAGUn71pVM55NbBpdOfpTf8mpC
  FZ+ujfUU+MG/IgdJYDitcwp2b7FqIokMqfD8HfaYEPJh/opOPNfMgM8e5XpehL8G
  yDH6AigsGp+lNBPXjqggFY76D3ApgKBXH9kjMOBvUyL1z7xcdcOm1WsjqdAl3Gc5
  9aFcS8tGj0dkepP4LAGM6omR6S+Ips56p7XNM/ytUOopxTn7w+YpZkvCFBOZ+x08
  XG1nzWCIRPxN2zUr9jmUMRlQQiAh+hm9ll6xUqnaK6Pnq6+btO1KaZhaE7hwGoQh
  5RDIoO5pOUDbpNCd1ag9SgNqfoz3/LwxBGy68nbaWJeSCafhrNjIM1I1mJ0=
  -----END RSA PRIVATE KEY-----"
