apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-prod
  namespace: football-live68-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  - host: api.cakeo.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-prod
            port:
              number: 80
