apiVersion: v1
kind: Service
metadata:
  name: backend-prod
  namespace: football-live68-prod
spec:
  type: ClusterIP
  selector:
    app: backend-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
